### ISSUE TITLE
Getting Error detected while processing function...

### ISSUE THREAD

**Issue by Neats29** [ElmCast/elm-vim#101]
`Error detected while processing function <SNR>47_BufWritePostHook..<SNR>47_UpdateErrors..<SNR>47_CacheErrors..278..277..SyntaxCheckers_elm_elm_make_GetLocLi
st..elm#Syntastic..elm#util#DecodeJSON:
line    1:
E121: Undefined variable: null
Error detected while processing function <SNR>47_BufWritePostHook..<SNR>47_UpdateErrors..<SNR>47_CacheErrors:
line   35:
E170: Missing :endfor
Error detected while processing function <SNR>47_BufWritePostHook..<SNR>47_UpdateErrors:
line   15:
E171: Missing :endif`

Getting the above errors regardless of what is in the elm file.
In my Vimrc, I only have: `let g:elm_format_autosave = 1` (I've installed elm-format)

Any ideas why I'm getting these errors?

**Comment by mvvvv** [comment]
Same kind of error :+1: 
Erreur détectée en traitant function <SNR>28_BufWritePostHook[4]..<SNR>28_UpdateErr
ors[15]..<SNR>28_CacheErrors[39]..18[1]..17[24]..SyntaxCheckers_elm_elm_make_GetLoc
List[1]..elm#Syntastic[12]..elm#util#DecodeJSON :
ligne    1 :
E121: Variable non définie : null
E15: Expression invalide : [{"tag":"SYNTAX PROBLEM","overview":"I ran into somethin
g unexpected when parsing your code!","subregion":null,"details":"I am looking for 
one of the following things:\n\n    a lower case name\n    whitespace","region":{"s
tart":{"line":56,"column":37},"end":{"line":56,"column":37}},"type":"error","file":
"/home/mv/elm/http.elm"}]
Erreur détectée en traitant function <SNR>28_BufWritePostHook[4]..<SNR>28_UpdateErr
ors[15]..<SNR>28_CacheErrors :
ligne   39 :
E170: :endfor manquant
Erreur détectée en traitant function <SNR>28_BufWritePostHook[4]..<SNR>28_UpdateErr
ors :
ligne   15 :
E171: :endif manquant


autosave activated too

**Comment by svrist** [comment]
Me too when opening any elm file
```
Error detected while processing function <SNR>39_BufReadPostHook..<SNR>39_UpdateErrors..<SNR>39_C
acheErrors..15..14..SyntaxCheckers_elm_elm_make_GetLocList..elm#Syntastic..elm#util#DecodeJSON:
line    1:
E121: Undefined variable: null
Error detected while processing function <SNR>39_BufReadPostHook..<SNR>39_UpdateErrors..<SNR>39_C
acheErrors:
line   35:
E170: Missing :endfor
Error detected while processing function <SNR>39_BufReadPostHook..<SNR>39_UpdateErrors:
line   15:
E171: Missing :endif
Error detected while processing function <SNR>39_BufReadPostHook:
line    4:
E171: Missing :endif
```

**Comment by ajhager** [comment]
I'm not sure how this has slipped through. I am at family for the holiday but will fix when I get home. Feel free to submit a PR if you figure it out before me.

**Comment by svrist** [comment]
I gave it a stab here: https://github.com/ElmCast/elm-vim/pull/103

**Comment by ajhager** [comment]
Alright, everyone please pull in the updated plugin and let me know if anything is still broken.

**Comment by jschomay** [comment]
I think so, but I'm still getting the error in #93 so it's hard to tell.

**Comment by mvvvv** [comment]
Yes, it's better. Thanks !

**Comment by dustinfarris** [comment]
Assuming this solution has been effective and that this issue can be closed now.
