### ISSUE TITLE
ElmErrorDetail in Ale?

### ISSUE THREAD

**Issue by jschomay** [ElmCast/elm-vim#105]
Hello, I've tried out the new Ale elm-make linting and it seems pretty nice.  One thing that I really miss though is being able to see the full error detail.  I don't really understand if something like "full details" is a concept in Ale, or if that is an elm-vim only thing  (@w0rp?).  Either way, is it possible to get the full error details functionality when using Ale instead of Syntastic?

Thanks!

**Comment by w0rp** [comment]
I'm not too familiar with the error format of `elm-vim` myself. I'd create an issue on my project with a description of how you would like to see the full details of an error. Maybe there's something that could be done for all plugins.

**Comment by jschomay** [comment]
Good news - this feature was just implemented in ale (https://github.com/w0rp/ale/issues/225) and it works great!!  For people still using syntastic, I highly recommend trying out ale.  It's as-you-type-linting is super useful, and now with this show details functionality, it works great with elm. :)
