### ISSUE TITLE
Syntastic checker likely to fail in Windows

### ISSUE THREAD

**Issue by elehner** [ElmCast/elm-vim#108]
To be honest, I haven't tested this myself, but the code uses `syntastic#util#DevNull()` to decide on a null file to use. If the user is on a Windows machine it will return the NUL file.  Currently, elm-make does not currently support NUL, noted here: https://github.com/elm-lang/elm-make/issues/125.

I ran into a similar error while making the Ale parser, so I thought I'd note it here. This I did test on my Windows machine, and it was failing since "nul" does not have the .js or .html extensions.  Easiest way to deal with this is to hard code '/dev/null'.

**Comment by dustinfarris** [comment]
Thanks for the heads up.  Please open an issue if this does indeed cause problems for you.
