### ISSUE TITLE
Enable GLSL highlighting inside GLSL code literals

### ISSUE THREAD

**Issue by lpil** [ElmCast/elm-vim#111]
Elm support GLSL code literals like so

```elm
vertexShader : Shader Vertex Uniforms { vcolor : Vec3 }
vertexShader =
    [glsl|

        attribute vec3 position;
        attribute vec3 color;
        uniform mat4 perspective;
        varying vec3 vcolor;

        void main () {
            gl_Position = perspective * vec4(position, 1.0);
            vcolor = color;
        }

    |]
```

It would be great to have these highlighted correctly (as github does here) :)

**Comment by ajhager** [comment]
Documenting that vim-markdown handles something like this for its code fence highlighting. https://github.com/plasticboy/vim-markdown/blob/94f85d78fd274a69694de26836b2fd0e7806e240/ftplugin/markdown.vim#L660

**Comment by dustinfarris** [comment]
Assuming this solution has been effective and that this issue can be closed now.
