### ISSUE TITLE
Jump to definition/show signature support

### ISSUE THREAD

**Issue by jschomay** [ElmCast/elm-vim#112]
Elm vim is a fantastic tool and I rely on it heavily.  But it is getting old now and is falling far behind other editors tooling.  Aside from syntax highlighting and linting, the number one feature I need in Elm is a way to see the signatures for any function or type under my cursor.  

I know there was some discussion on this last year, but it seems to have stalled completely.  I think this is a major feature that needs some attention and priority, and I think we have the tools to make it work (especially with vim 8 async capabilities), I just don't know how myself.

Looking through the issues, many of theme seem to be related to problems with Syntastic.  I had similar problems, so I switched to Ale and it is working swimmingly for me.  My suggestion is to prioritize this feature I am suggesting and not get bogged down by trying to support syntastic for now, and it will put elm-vim back on top of the game.

Thank you.

**Comment by mwgkgk** [comment]
Hey I'm just going to jump in here to point out ctags, which is an executable that generates a tag file for Vim to use. Here's a ctags question on this issue tracker: https://github.com/ElmCast/elm-vim/issues/24 

More links: https://github.com/kbsymanz/ctags-elm https://github.com/bitterjug/vim-tagbar-ctags-elm

**Comment by jschomay** [comment]
Good call @mwgkgk!  You're right, ctags are great for this.  I haven't used them before, but I just tried them out with the ctags-elm plugin and auto-tag and they work well, both for jump to definition, and for showing a functions signature (with g] or :tselect myFn).

It's not quite as nice of an experience as :elmShowDocs, but it gets me what I want.  I'll mark this closed, thanks.
