### ISSUE TITLE
Is it possible to have an import list without exposing highlighted as erroneous?

### ISSUE THREAD

**Issue by hoelzro** [ElmCast/elm-vim#12]
For example:

```elm
import Mouse (clicks) -- it would be nice if '(clicks)' were in red
import Mouse exposing (clicks) -- OK!
```

I've seen other Vim syntax files do similar things; I'm afraid I'm not good enough at Vim to know how to do it off the top of my head.

**Comment by ajhager** [comment]
Real time syntax error highlighting is definitely possible. I will give it a try. Thanks for the request.

**Comment by hoelzro** [comment]
@ajhager Thanks for the quick response!  It's ok if you can't manage full errors (I imagine that's a quite a bit more work); I'm more concerned about the use case I mentioned, because I seem to still do it all the time. =)
