### ISSUE TITLE
Command already exists, append ! to replace it

### ISSUE THREAD

**Issue by jaischeema** [ElmCast/elm-vim#123]
I have been using this plugin along with https://github.com/tpope/vim-rails for some time but never had any issues until yesterday when I upgraded all of my plugs. Drilled it down to the combination of these two, wasn't sure which repo I should be creating this bug in, apologies if I picked the wrong one 😄 

Environment: macOS 10.12.5, Neovim 0.20, latest version of elm-vim and vim-rails plugin using vim-plug package manager.

**Comment by jweir** [comment]
The issue appears to be related to these commands getting loaded more than once
https://github.com/ElmCast/elm-vim/blob/master/ftplugin/elm.vim#L44-L51

**Comment by jweir** [comment]
Here is the commit in `vim-rails` that introduces the error in `elm-vim`
https://github.com/tpope/vim-rails/commit/f095e38c5653f077

**Comment by jaischeema** [comment]
@jweir I am not well versed in vimscript at all, any recommendations to fix this? If this behaviour should be changed in vim-rails, I can create an issue there. Thanks for all your help, much appreciated.

**Comment by jweir** [comment]
This is the issue I opened with vim-rails https://github.com/tpope/vim-rails/issues/493

@tpope explains the issue as:

> My guess is the lack of a b:undo_ftplugin in ftplugin/elm.vim is interacting poorly with rails.vim providing a default if it doesn't exist. Ideally vim-elm would add a b:undo_ftplugin, as that really is the best practice, but perhaps rails.vim should be handling that edge case differently.

So it seems this plugin needs `b:undo_ftplugin` ... now to understand what that means and how to do it.

**Comment by tpope** [comment]
`command!` will treat the symptoms and you probably want it regardless.

**Comment by jesse-c** [comment]
FWIW I'm facing this issue too as of a week ago or so when I also updated all my Plug-installed plugins. I'm not sure which other plugin(s) are interacting badly, as I've got so many running I haven't taken the time to narrow it down. 😅

**Comment by tpope** [comment]
Since it was never explained, `b:undo_ftplugin` is a string containing a series of commands to run when switching *away* from a filetype. It undoes everything the ftplugin did. It tends to look something like this:

```viml
let b:undo_ftplugin = 'setl option1< option2<|nunmap <buffer> somemap|delcommand SomeCommand'
```
The original issue was because the ftplugin was getting activated a second time, and then conflicting with the commands defined the first time.
