### ISSUE TITLE
Autoload functions failure

### ISSUE THREAD

**Issue by Libbum** [ElmCast/elm-vim#133]
On startup, I'm getting this error:

> Error detected while processing /home/tim/.config/nvim/plugged/elm-vim/ftplugin/elm.vim:            
> line   94:                                                                                          
> E117: Unknown function: elm#FindRootDirectory                                                       
> E116: Invalid arguments for function join([   elm#FindRootDirectory().'/src',   elm#FindRootDirector
> y().'/elm-stuff/packages/**/src',   &g:path ], ',')                                                 
> E15: Invalid expression: join([   elm#FindRootDirectory().'/src',   elm#FindRootDirectory().'/elm-st
> uff/packages/**/src',   &g:path ], ',') 

So it seems that the `elm#FindRootDirectory()` in `autoload/elm.vim` has not been successfully loaded.

Using Arch linux, neovim, vim-plug. Using vim-polyglot but have `let g:polyglot_disabled = ['elm']` in my vimrc.
Anyone have suggestions on how to track the issue in my setup?

**Comment by arnau** [comment]
I have the same error.

* macOS 10.12.6
* vim 8.0 (2016 Sep 12, compiled Sep 27 2017 06:40:24)
* vim-plug 0.9.1
* I also have `let g:polyglot_disabled = ['elm']`.

```
Error detected while processing /Users/arnau/.vim/plugged/elm-vim/ftplugin/elm.vim:
line   94:
E117: Unknown function: elm#FindRootDirectory
E116: Invalid arguments for function join([   elm#FindRootDirectory().'/src',   elm#FindRootDirectory().'/elm-stuff/packages/**/src',   &g:path ], ',')
E15: Invalid expression: join([   elm#FindRootDirectory().'/src',   elm#FindRootDirectory().'/elm-stuff/packages/**/src',   &g:path ], ',')
```

It worked just fine until I upgraded vim today. Any idea why?

**Comment by arnau** [comment]
@Libbum so after a bit of try and error, I found that the order matters when loading `vim-polyglot` and `elm-vim`.

Fails:

```
Plug 'sheerun/vim-polyglot'
let g:polyglot_disabled = ['rust', 'elm']
Plug 'elmcast/elm-vim'
```

Works:

```
Plug 'elmcast/elm-vim'
Plug 'sheerun/vim-polyglot'
let g:polyglot_disabled = ['rust', 'elm']
```

Also works: 

```
Plug 'sheerun/vim-polyglot'
let g:polyglot_disabled = ['rust']
Plug 'elmcast/elm-vim'
```

**Comment by Libbum** [comment]
@arnau excellent catch! Can confirm that loading `Plug 'elmcast/elm-vim'` before `Plug 'sheerun/vim-polyglot'` works for me too.

Are you happy for me to close this issue then?

**Comment by arnau** [comment]
I think so 👍

**Comment by Libbum** [comment]
Great. Thanks for working that out. I might make a quick PR to update the readme about this for other people

**Comment by arcseldon** [comment]
https://stackoverflow.com/a/46669126/1882064
