### ISSUE TITLE
ElmMakeMain on save

### ISSUE THREAD

**Issue by quangv** [ElmCast/elm-vim#138]
I am trying to run ElmMakeMain on save/autosave.

I've added this line to the elf_format_autosave part in `ftplugins/elm.vim`

```
 autocmd BufWritePost *.elm call elm#Make("src/Main.elm")
```
So that part now is:

```
" Elm code formatting on save
if get(g:, 'elm_format_autosave', 1)
  augroup elmFormat
⇥ autocmd!
⇥ autocmd BufWritePre *.elm call elm#Format()
⇥ autocmd BufWritePost *.elm call elm#util#EchoStored()
  autocmd BufWritePost *.elm call elm#Make("src/Main.elm")
   augroup END
endif
```

Which works nicely!

<img width="616" alt="1" src="https://user-images.githubusercontent.com/1171187/31450067-85ead2c2-ae76-11e7-9e06-8c7fb2ab7acd.PNG">

Unfortunately, limitations include,
- having to hardcode path to `Main.elm`, 

I just started Elm development, and `elm-vim` is a godsend, thank you. I might be using it wrong.

Please let me know if there's a better way to do this. However, it's working nicely for me, love getting compile messages within VIM, so don't have to go to the browser to see bugs.

(fyi I'm using `create-elm-app` so code is in `src/` and `:ElmMakeMain` doesn't work out of the box.)

**Comment by blurrcat** [comment]
Thanks @quangv !
I find it enough to just compile the current buffer on save. `elm#Make()` and you don't have to hardcode any path.

**Comment by dustinfarris** [comment]
Assuming this solution has been effective and that this issue can be closed now.
