### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by r03** [ElmCast/elm-vim#150]
Hi, just wondering if this project is still alive? I see a lot of PR’s but no response. 
Thanks for making this plugin!

**Comment by ajhager** [comment]
Thanks for reaching out! Working at a startup that doesn't use Elm has made it difficult to find the time to attend to this project. I am in the process of cleanup and pulling PRs into the [unstable](https://github.com/ElmCast/elm-vim/tree/unstable) branch, as well as looking for others to help with day to day stewardship of the project.

**Comment by mdxprograms** [comment]
@ajhager Can we merge this one to the current master branch? https://github.com/ElmCast/elm-vim/pull/144
Seems to be a common issue and a simple fix to get it out of the way.
Also I can help contribute if you need more maintainers.

**Comment by dustinfarris** [comment]
@ajhager can i get collaborator status on this project and help merge stuff in?

**Comment by dustinfarris** [comment]
Awesome, thanks Joseph!
