### ISSUE TITLE
on error it breaks my vim 

### ISSUE THREAD

**Issue by dowan** [ElmCast/elm-vim#158]
Hi, 

when i have a syntax error, my display is fucked up and a stay blocked where error was displayed

it happens when i split my vim 

if anyone know how i can fix that ^^ 

Thanks

Dowan

**Comment by ckipp01** [comment]
@dowan Do you by chance have as screenshot to show exactly what is happening?

**Comment by dowan** [comment]
Hi, i just tried to reproduce it but i can't :/ ^^ 

sorry i close that issue if it happens to me again, i'll think to make a screenshot

sorry and thanks

Dowan
