### ISSUE TITLE
Is elm-vim plug-in abandoned?

### ISSUE THREAD

**Issue by ogirginc** [ElmCast/elm-vim#189]
Hi! It seems no one is merging any pull requests. Is it safe to assume elm-vim is abandoned at this point? Thanks :)

**Comment by jcornaz** [comment]
@ogirginc, The absence of answer to your question after 2 months is quite explicit I think.

If you are looking for an alternative, a fork of this library is maintained here: https://github.com/Zaptic/elm-vim
