### ISSUE TITLE
:ElmMake > elm-make fails

### ISSUE THREAD

**Issue by gamecubate** [ElmCast/elm-vim#2]
Calling :ElmMake on my current .elm file seems to fail. It does create a package.json file but fails to download anything.

```
:ElmMake
elm-make: building ... Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 2.1.0

Do you approve of this plan? (y/n) elm-make: <stdin>: hGetLine: end of file
Press ENTER or type command to continue
```

**Comment by ajhager** [comment]
Thanks. I will try to add support for that. You can run `elm-package install` outside of vim when you update your dependencies in the mean time.

**Comment by gamecubate** [comment]
OK thanks for the advice. I thought it was some incompatibility between MacVim and your bundle. <relieved>
