### ISSUE TITLE
Generalize running all commands from the root directory

### ISSUE THREAD

**Issue by ajhager** [ElmCast/elm-vim#23]
Most commands will fail if vim's pwd isn't the root (where elm-stuff is).

**Comment by SamOfFinland** [comment]
Where should I put my Main.elm file if I want to use :ElmMakeMain?

Now I have it in <project>/src/Main.elm path. When I run :ElmMakeMain in Vim with pwd in <project>/src/ elm-make tries to install elm-stuff to <project>/src/.

And does elm-package.json "source-directories" affect to this plugin?

**Comment by gabrielflorit** [comment]
@SamOfFinland I have it in `root`, and everything else in `src`. That works well with `:ElmMakeMain`.

**Comment by SamOfFinland** [comment]
@gabrielflorit Ok thanks! I'll try that.

**Comment by 0xR** [comment]
@gabrielflorit This does not work for me.

I think elm-vim should recursively look for elm-stuff in parent dirs and run `elm-make Main.elm` in that folder. I'm not familiar enough with vim-script to submit a PR though.

**Comment by toupeira** [comment]
If you have an Elm project nested inside another project [vim-rooter](https://github.com/airblade/vim-rooter) can be used as a workaround, you just have to make sure `elm-package.json` appears in `g:rooter_patterns` before `.git` or whatever you use as a marker for the main project directory.

**Comment by ajhager** [comment]
We now run elm-make and elm-oracle from the root project directory.

Fixed in 80714bacd672310c5b5e53d2c7ee96b0acbcacb8
