### ISSUE TITLE
Support and / or docs for common third party vim packages

### ISSUE THREAD

**Issue by ajhager** [ElmCast/elm-vim#25]
YouCompleteMe, etc.

**Comment by suzuki11109** [comment]
I have a work around for autocomplete.
just set `:imap . .<c-x><c-o>`
and it works. :)

**Comment by suzuki11109** [comment]
I found another solution.
you can make YCM to support elm files with
```
let g:ycm_semantic_triggers =  {
  ...
  \   'elm' : ['.'],
}
```

**Comment by aliceriot** [comment]
@suzuki11109 maybe I'm not understanding your solution properly, if I paste this into my `.vimrc`:

```
imap . .<c-x><c-o>
let g:ycm_semantic_triggers =  {
  \   'elm' : ['.'],
}
```

I get a warning about improperly formed dictionaries. I'd love to get YCM working for Elm, any chance you could post your `.vimrc` as a gist?

**Comment by aliceriot** [comment]
@suzuki11109 nevermind! I got it working with the following:

```
let g:ycm_semantic_triggers = {
     \ 'elm' : ['.'],
     \}
```

I would be really cool to incorporate this into the `README.md`!

**Comment by ajhager** [comment]
Will do. Thanks for the update!

**Comment by suzuki11109** [comment]
@aliceriot 👍

**Comment by toupeira** [comment]
Configuration for neocomplete:

```vim
call neocomplete#util#set_default_dictionary(
  \ 'g:neocomplete#sources#omni#input_patterns',
  \ 'elm',
  \ '\.')
```

**Comment by ajhager** [comment]
I have added all these suggestions to the README, so I am going to close this issues. If you have any other suggestions or corrections, please let me know.
