### ISSUE TITLE
Running :ElmMake with or without filename fails with generic help message from elm-make-unwrapped

### ISSUE THREAD

**Issue by localshred** [ElmCast/elm-vim#3]
Assuming this isn't much more than PEBKAC, but running `:ElmMake` with or without a filename shows the help message for `elm-make-unwrapped`. I just cloned this plugin a few minutes ago and am using it with pathogen. I haven't added any customizations to my `.vimrc` for this plugin yet.

I'm running `elm-make` version 0.1.2, Elm Platform 0.15.

<img width="1552" alt="screen shot 2015-07-12 at 1 40 26 pm" src="https://cloud.githubusercontent.com/assets/47752/8639607/773be908-289c-11e5-843b-721922260775.png">

When I run `elm-make Counter.elm` from the terminal I am receiving the error output I expected:

<img width="1552" alt="screen shot 2015-07-12 at 1 49 03 pm" src="https://cloud.githubusercontent.com/assets/47752/8639616/c72fc88a-289c-11e5-81eb-1a2b0bcb2f7c.png">

**Comment by localshred** [comment]
Oh, and just to be clear:

```shell
$ cd ~/.vim/bundle/elm-vim
$ git rev-parse HEAD
aa8745fa8d328c488114152f8a67fd0dbd0c6bfa
```

**Comment by ajhager** [comment]
I am sorry, but elm-vim requires Elm 15.1 which added many features that the plugin depends on. I will need to add a note about that in the README. If you still have issues after upgrading, please let me know.

**Comment by localshred** [comment]
Ah! Ok will do. Thanks for the great plugin!
