### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by viswaug** [ElmCast/elm-vim#32]
I tried this plugin with Vundle by adding (Plugin 'elmcast/elm-vim.git') to my .vimrc and running ":PluginInstall", but couldn't get it to work.

The error on running ":ElmRepl" is "E492: Not an editor command: ElmRepl"

The ":PluginList" command lists the plugin in. The files have been checkout into the ~/.vim/bundle folder. But the ":scriptnames" command does not list the "elm.vim" file in the plugin folder as being loaded. The ":func ElmRepl" errors with "E123: Undefined function: ElmRepl".

Any way to troubleshoot why the plugin functions are not getting loaded? Any log files anywhere i should look into?

**Comment by ajhager** [comment]
I will attempt to test this out. Thanks for the report.

**Comment by ajhager** [comment]
Thank you for posting this. You can track progress on this in #46
