### ISSUE TITLE
Primed keyword identifier highlighted as keyword 

### ISSUE THREAD

**Issue by bitterjug** [ElmCast/elm-vim#33]
So I have 

```
   input [ type' = ... ]
```

And the type function is highlighted as **type**' because `type` is a keyword, but `type'` is really just a normal identifier.

**Comment by ajhager** [comment]
Hmm, this seems to be an issue about how vim matches keyword syntax words. Vim doesn't see the ' as part of the world. I will look into how other languages implement this, perhaps haskell-vim handles this better.

Thanks!

**Comment by ajhager** [comment]
Closing for now because I don't think I can fix this issues, but I am making a note of it.
