### ISSUE TITLE
How is `:ElmTest` supposed to work?

### ISSUE THREAD

**Issue by lydell** [ElmCast/elm-vim#34]
First off, the case where you run `:ElmTest` without arguments. “If no file is given it attempts to run the tests in 'Test[filename].elm'”. That seems to be implemented as `"Test" . expand("%")`. `:help expand()` says that `%` means “current file name”. I’m not a vim expert, but as far as I understand “current file _path_” would be more accurate. If I run `:echo expand("%")` in vim, it seems like paths relative to `:pwd` are returned, such as `Main.elm` or `src/Foo.elm`. gvim seems to output absolute paths, such as `/home/lydell/elm-foo/Main.elm`. So I think the code should be something like `expand("%:h") . "/Test" . expand("%")` (see `:help expand()` for more information on what `:h` and `:t` does).

---

Secondly, I’m quite new to `elm-test`. `elm-test init` creates a `src/` directory and a `tests/` directory. Seems like the suggested way of organizing things is to put source files and tests in different directories. Also, it is not quite clear to me how to split your tests up into several files, since you point `elm-test` to a “runner” file, not the file where the actual tests are written.

`:ElmTest` seems to suggest that if you create a file `Foo.elm`, you should create a file `TestFoo.elm` next to it (as opposed to into a separate `tests/` directory), and put unit tests for `Foo.elm` in there. But what about the “runner” file?

For now, I ignore `:ElmTest` and run my entire test suite using `elm-test` on the command line whenever I want to run tests, because I don’t understand the use case for `:ElmTest`. Mind clarifying? :)

**Comment by ajhager** [comment]
Thanks for the question and insight! The :ElmTest command was added quite a long time ago, and the tooling has evolved since then. The elm-vim testing code clearly needs a revamp, and I will use this issue to track.

**Comment by ajhager** [comment]
For now :ElmTest will run elm-test on the file you are editing if it contains a consoleRunner, or it will run without arguments in your root project, which automatically runs `elm-test tests/TestRunner.elm`. This will be improved and refined in time, but it is a start. Happy coding!

Fixed in a36c81c3625dae59b2c738521e82facc52d40893.
