### ISSUE TITLE
Syntastic integration

### ISSUE THREAD

**Issue by toupeira** [ElmCast/elm-vim#40]
I currently use these settings:

```vim
let g:elm_jump_to_error = 0
let g:elm_make_show_warnings = 1
let g:elm_make_output_file = '/dev/null'

let g:syntastic_elm_checkers = [ 'elm_make' ]
```

...in combination with this wrapper in `~/.vim/syntax_checkers/elm/elm_make.vim`:

```vim
if exists('g:loaded_syntastic_elm_elm_make_checker')
    finish
endif
let g:loaded_syntastic_elm_elm_make_checker = 1

let s:save_cpo = &cpo
set cpo&vim

function! SyntaxCheckers_elm_elm_make_GetLocList() dict
    call elm#Make()
    let fixes = getqflist()
    call setqflist([])
    cclose

    return fixes
endfunction

call g:SyntasticRegistry.CreateAndRegisterChecker({
    \ 'filetype': 'elm',
    \ 'name': 'elm_make',
    \ 'exec': 'elm-make'})

let &cpo = s:save_cpo
unlet s:save_cpo
```

Which seems to work fine so far, but it would be cleaner if I could get the list of `fixes` directly from either `elm#Make()`, or maybe a new function `elm#Compile()` which extracts the common parts. What do you think?

**Comment by ajhager** [comment]
I completely agree. Let me see what I can come up with.

**Comment by ajhager** [comment]
I have restructured how elm#Make works and added support for syntastic out of the box. I would suggest using the following settings:

```vim
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1

let g:elm_syntastic_show_warnings = 1
```

You should be able to remove your custom code. Let me know if you run into any issues. Thanks for getting me started in the right directions!

**Comment by toupeira** [comment]
Thanks, works great!
