### ISSUE TITLE
Undo is painful

### ISSUE THREAD

**Issue by hulufei** [ElmCast/elm-vim#54]
Hi, I was wondering if your guys encounter this problem, for example, use `cw` to replace a word, saved with elm-format, then if I want to undo the replacement, it needs press `u` multi times.

**Comment by ajhager** [comment]
I thought I had this working correctly, so let me take a look.

**Comment by hulufei** [comment]
@ajhager Glad to know you're working correctly, so I reviewed my `.vimrc`, and found I have an undo plugin [mbbill/undotree](https://github.com/mbbill/undotree), seems like this plugin cause the problem.

**Comment by schnittchen** [comment]
It's the same for me, except I do not use the undotree plugin.

**Comment by ajhager** [comment]
Fixed with 2a8eb1cb9d922e02ad182ebbe066448cbe8233f9. Please let me know if this has not fixed the issue for you.
