### ISSUE TITLE
Current window was closed error on elm-make

### ISSUE THREAD

**Issue by svanderbleek** [ElmCast/elm-vim#55]
```
elm-make: building... found 2 errors
Error detected while processing function elm#Make:
line   17:
E924: Current window was closed
```

**Comment by svanderbleek** [comment]
Seems to be because of jump combined with syntastic auto, setting it to 3 fixed it:

```
let g:syntastic_auto_loc_list = 3
```

**Comment by josephbuchma** [comment]
Thank you sooo much @svanderbleek. I had same issue with vim-go commands.

**Comment by dustinfarris** [comment]
Assuming this solution has been effective and that this issue can be closed now.
