### ISSUE TITLE
Missing :ElmFormat

### ISSUE THREAD

**Issue by chalmagean** [ElmCast/elm-vim#72]
For some reason `:ElmFormat` seems to be gone. I have not function I can call and nothing happens on save.

**Comment by benmoss** [comment]
if you run `:!which elm-format` what do you see?

**Comment by chalmagean** [comment]
Figured it out. It was due to the vim-polyglot plugin which was loading a different version of elm-ivm.

**Comment by cuducos** [comment]
@chalmagean I guess I have the same issue here (as `:ElmFormat` seems to be gone and I have `sheerun/vim-polyglot` installed).

Can you share how you fixed that in your case? Many thanks.

**Comment by ajhager** [comment]
vim polyglot comes with an alternative elm vim plug, so you need to disable it with `let g:polyglot_disabled = ['elm']`.

**Comment by cuducos** [comment]
Yay, many thanks @ajhager ; )
