### ISSUE TITLE
Comments not properly highlighted.

### ISSUE THREAD

**Issue by jottr** [ElmCast/elm-vim#73]
I'm not sure if some other plugin could be interfering, but for me the syntax highlighting is incorrect for ~~multiline~~ comments. 
See screenshot:

<img width="690" alt="screen" src="https://cloud.githubusercontent.com/assets/2744198/17828199/5bae87d0-668b-11e6-939e-7e9c5266dd0a.png">

I ran `:PluginUpdate` to make sure I have the most recent version of `elm-vim`.

**Comment by rohanorton** [comment]
Hi jottr,

I'm not able to reproduce this with latest elm-vim. Could you tell me if you're still experiencing the issue if you run vim with the following config (using `-u` flag):

```vim
set nocompatible
set encoding=utf-8
syntax enable

call plug#begin('~/.vim/plugged')
Plug 'ElmCast/elm-vim'
call plug#end()
```

If comment syntax highlighting is correct with this config then it is most likely another plugin interfering somehow. Try commenting out potential offenders in your vimrc to find which one it might be.

**Comment by jottr** [comment]
Thank you @rohanorton, I just checked with your config as suggested, and you were right, it must be some other plugin interfering with the highlighting.

**Comment by zack** [comment]
Had this same problem, `kien/rainbow_parentheses` was the problem.
