### ISSUE TITLE
elm-format autosave didn't work for me

### ISSUE THREAD

**Issue by gilesbowkett** [ElmCast/elm-vim#80]
caveat: I can live without it. just reporting this with the assumption that you'd want to know.

I got this error whenever I attempt to save a file:

```
Error detected while processing function elm#util#EchoStored:
line    2:
E488: Trailing characters
```

my guess is that the problem may come from the fact that I didn't install elm with `-g`. I'm just very skittish about installing anything globally. but, if that doesn't explain it, I'm on vim 7.3, and the relevant section of my .vimrc looked like this:

```
" elm-format setup; from https://github.com/avh4/elm-format
call plug#begin('~/.vim/plugged')
Plug 'elmcast/elm-vim'
call plug#end()
let g:elm_format_autosave = 1
```

**Comment by ajhager** [comment]
This looks like a bug in something I merged today. Thanks for the report. What operating system are you on?

**Comment by gilesbowkett** [comment]
god, this is so embarassing. OS X 10.8.5, `vim --version` gives me: `VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 23 2012 13:50:52)`. I hate upgrading and I've got some graphics stuff on this machine I really like.

**Comment by ndonze** [comment]
Seeing the same issue.

OS X 10.11.6
VIM 7.3

No issue running `:ElmFormat` directly. Error appears when writing and formatting automatically on save via `let g:elm_format_autosave = 1`.

Disabling format on write via `let g:elm_format_autosave = 0` stops the error. Commenting out the following line in `autoload/elm/util.vim` also stops the error:

`call function('elm#util#' . s:echo_func_name)(s:echo_title, s:echo_msg)`

**Comment by rofrol** [comment]
I got this today "error why processing Elm#format".

Removed elm-vim and `:PlugInstall`.

**Comment by rofrol** [comment]
Again the same problem. Goting with

```
let g:elm_format_autosave = 0
autocmd BufWritePost *.elm silent! !elm-format --yes %:p
```
