### ISSUE TITLE
Does not work in vim 8

### ISSUE THREAD

**Issue by zwhitchcox** [ElmCast/elm-vim#83]
This does not appear to work on vim 8

**Comment by ajhager** [comment]
Yeah, there seem to be some issues with vim 8. I am investigating.

**Comment by zwhitchcox** [comment]
For me, adding 

```vim
command -nargs=? -complete=file ElmMake call elm#Make(<f-args>)                                                                       
command ElmMakeMain call elm#Make("Main.elm")                                                                                         
command -nargs=? -complete=file ElmTest call elm#Test(<f-args>)                                                                       
command ElmRepl call elm#Repl()                                                                                                       
command ElmErrorDetail call elm#ErrorDetail()                                                                                         
command ElmShowDocs call elm#ShowDocs()                                                                                               
command ElmBrowseDocs call elm#BrowseDocs()                                                                                           
command ElmFormat call elm#Format()       
```

to my `.vimrc` made it work

**Comment by zwhitchcox** [comment]
Also, it's giving me the wrong file name...like, it gives me the error on the right file name as well, but it also displays on the wrong file...errors that I don't have

**Comment by zwhitchcox** [comment]
Like make a mistake in a sub file of Main.elm, and it will show the error in Main.elm...The compiler gets it right though

**Comment by ajhager** [comment]
I have merged a couple of changes. Could you update the plugin and let me know if both of those issues are now fixed?

**Comment by zwhitchcox** [comment]
Now, I'm getting an error when I try to elm format...see #82

**Comment by zwhitchcox** [comment]
Fixed by adding 
`filetype plugin indent on` to my vimrc

Thank you!!

**Comment by slashmili** [comment]
@zwhitchcox it didn't help in my case

the commands like `ElmFormat` are not defined unless I add lines like this

```
command ElmFormat call elm#Format()
```

Anyone else having problem with it?
