### ISSUE TITLE
Screenshots or Cast of Autocomplete

### ISSUE THREAD

**Issue by iammerrick** [ElmCast/elm-vim#92]
Would love to see what autocompletion is supposed to look like... Currently I get something like this:

![screen shot 2016-10-19 at 1 23 35 pm](https://cloud.githubusercontent.com/assets/109635/19534089/aeeb22c0-95ff-11e6-9f6f-e15012928d25.png)

If this is as intended, that is totally ok. Since there is no reference on the site or cast I wasn't sure if this was as intended.

I would have expected something more like what I get with TernJS + YCM:

![image](https://cloud.githubusercontent.com/assets/109635/19534101/bbe3818e-95ff-11e6-9937-14db8c8dd9c8.png)

Notice how TernJS + YCM offers a similar experience to Atom?

**Comment by ajhager** [comment]
You can turn on detailed auto-complete with this config option:

```vim
let g:elm_detailed_complete = 1
```

If there is something you would like to see added or changed to the complete functionality, please let me know.

**Comment by iammerrick** [comment]
@ajhager dude this is amazing!! Thanks for the quick reply!!!

**Comment by haasDev** [comment]
anything that does a similar thing for records that I've declared?  For instance if I have a record of 

```
myRecord = { thing1 = 'thing1'
                     , thing2 = 'thing2'
                     }
```
I would like to be able to say myRecord and when I hit 'dot' I would get a list with thing1 and thing2 as options.

**Comment by ajhager** [comment]
Unfortunately, because of the way that elm-oracle gets data about code, elm-vim can only complete things from 3rd-party libraries. Anything in your own project will not be completed.
